language: python
env:
  - R_LIBS_USER=$TRAVIS_BUILD_DIR/R
python:
  - 2.6
  - 2.7
before_install:
  - sudo apt-get install -qq r-base-core
  - Rscript -e "options(repos=structure(c(CRAN='http://cran.r-mirror.de')));install.packages('knitr',lib='$R_LIBS_USER')"
install:
  - pip install -r testapp/requirements.txt
  - pip install .
script: nosetests
