language: python
python:
  - 2.7
before_install:
  - sudo apt-get install -qq r-base-core
  - sudo Rscript -e "options(repos=structure(c(CRAN='http://cran.r-mirror.de')));install.packages('knitr')"
install:
  - pip install git+git://github.com/SimonSapin/Flask-FlatPages/
  - pip install -r testapp/requirements.txt
  - python setup.py install
script: nosetests
